Attempt at terminal tips xD
pesos/pesos.github.io pull request #23
Opened 2019-09-13 18:33 UTC by metonymic-smokey

Just a draft of a few tips I wanted to share.
Review plis for changes and suggestions xD
I'll add more tips along the same lines if these are okay.

Thanks!

2019-09-13 18:35 UTC, metonymic-smokey commented
@tfidfwastaken since this PR is a little messy with so many commits, do you want me to rebase and squash all these into 1?

2019-09-15 05:45 UTC, tfidfwastaken commented
@metonymic-smokey No need to squash and rebase, a slightly messy commit history is not a big deal for us

2019-09-15 06:05 UTC, tfidfwastaken requested changes
Great additions!
Just make the minor changes I requested and we'll get it merged soon

2019-09-15 06:05 UTC, tfidfwastaken commented on _posts/2018-09-08-terminal-tips.md
> +## Reusing previous commands
This section isn't 100% clear to me
> reusing the previous command with the current one

What exactly does 'one' refer to here? Reuse previous command with the current ?command¿ 
I have the same confusion with your `?!` tip.

Maybe you can improve the description a bit and add an example for `?!` to make it more clear?

2019-09-15 06:05 UTC, tfidfwastaken commented on _posts/2018-09-08-terminal-tips.md
> +To avoid having a command added to your .bash_history file, prefix it with a space i.e. go with `  [command]` instead of `[command]`.
Also while you are making the above change, markdown seems to not be adding in the space for ` [command]`
I think you'll have to use`<code>&nbsp;command</code>` instead to make it work

2019-09-16 16:18 UTC, metonymic-smokey commented on _posts/2018-09-08-terminal-tips.md
> +## Reusing previous commands
@tfidfwastaken resolved the !! tip.
Will add the ?! tip later.
Is it okay now?

Thanks!

2019-10-17 13:50 UTC, tfidfwastaken commented on _posts/2018-09-08-terminal-tips.md
> +## Reusing previous commands
Yeah looks good
I added an example for more clarity
LGTM

2019-10-17 13:51 UTC, tfidfwastaken approved these changes

2019-10-17 13:53 UTC, merged